Added a notebook that tests the mlflow tracking feature that is set to release in 1.6.0
mlrun/test-notebooks pull request #76
Opened 2023-12-07 14:56 UTC by amit-elbaz

2023-12-11 20:18 UTC, MichaelSkralivetsky commented on test-mlflow-tracking/test-mlflow-tracking.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    ! pip uninstall mlrun -y
</pre><p>no need, remove</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/test-notebooks/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2023-12-11 20:18 UTC, MichaelSkralivetsky commented on test-mlflow-tracking/test-mlflow-tracking.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    ! pip install mlrun==1.6.0-rc11
</pre><p>no need, remove, this anyway will be running only on 1.6.0-rc12 and newer during automatic tests</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/test-notebooks/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-12-11 20:20 UTC, MichaelSkralivetsky requested changes
no need to uninstall/install mlrun, automation is taking care of this

2023-12-12 06:40 UTC, amit-elbaz commented
@MichaelSkralivetsky Fixed

2023-12-12 08:27 UTC, merged